### ISSUE TITLE
Can FileBrowseAndUploadWidget be used with standard ImageField/FileField?

### ISSUE THREAD

**Issue by int-ua** [DjangoAdminHackers/django-filebrowser-browse-upload-field#1]
I've checked the code and looks like it depends on the field. But maybe you know a way?

**Comment by andybak** [comment]
Do you mean - "can this be used without using Django filebrowser"?

If that is what you mean then the answer is "probably not". Although the upload stuff might work without it - the 'browse for existing' functionality depends on Django-filebrowser and they are deeply intertwined.

If you're asking something different, can you clarify?

**Comment by int-ua** [comment]
No, I mean using `FileBrowseAndUploadWidget` without `FileBrowseAndUploadField`, on a standard ImageField or FileField or an already subclassed custom ImageField. Basically, is it possible to have existing files selection without having to make migrations for `FileBrowseAndUploadField`.

**Comment by andybak** [comment]
Probably but you'd have to look at the overridden methods in FileBrowseAndUploadField and do something similar in your custom class

(or alternatively - add your custom class's stuff in a new subclass of FileBrowseAndUploadField!)
